### PR TITLE
Revamp travis config (will cython extensions build cleanly now?).

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by arokem** [comment]
Do you understand this? 

On the one hand, the error: https://travis-ci.org/mbeyeler/pulse2percept/jobs/305044459#L1046

On the other: https://travis-ci.org/mbeyeler/pulse2percept/jobs/305044459#L847

Suggesting that dask was successfully installed. Mystifying.

**Comment by mbeyeler** [comment]
Could it be a version issue? `has_dask` will also be False if either `dask.multiprocessing` or `dask.delayed` is not around: https://github.com/uwescience/pulse2percept/blob/master/pulse2percept/utils.py#L25

**Comment by mbeyeler** [comment]
On the other hand, pip installs dask 0.16 - seems up to date.... idk

**Comment by arokem** [comment]
Maybe we need dask.distributed to be present? I'll try that.

**Comment by mbeyeler** [comment]
Nice, that did it!

**Comment by mbeyeler** [comment]
One minor remaining issue is that `retina.pyx` does not show up in the coverage report... Do you know how to fix that, too?

**Pull request closed without merging**
